service:
  name: back-api
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: ">=1.1.0 <2.0.0"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  stackName: ${opt:stack-name, 'vizir-staging'}
  stage: ${opt:stage, 'staging'}
  runtime: nodejs12.x
  region: sa-east-1
  timeout: 30
  memorySize: 192
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  app:
    handler: handler.run
    events:
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
